# Sample .travis.yml for R projects.
#
# See README.md for instructions, or for more configuration options,
# see the wiki:
#   https://github.com/craigcitro/r-travis/wiki

language: r
cache: packages
r:
#  - oldrel
  - release
#  - devel
sudo: false


notifications:
  slack: usgs-cida:Cx7V5bobjgTw7U30GYzTvtHa 
    on_success: change
    on_failure: change 